SELECT
    "matchId" as match_id,
    "id" as id,
    "eventId" as event_id,
    "minute" as minute,
    "second" as second,
    "teamId" as team_id,
    "playerId" as player_id,
    "x" as x,
    "y" as y,
    "expandedMinute" as expanded_minute,
    "period" as period,
    "type" as type,
    "outcomeType" as outcome_type,
    "isTouch" as is_touch,
    "endX" as end_x,
    "endY" as end_y,
    "goalMouthZ" as goal_mouth_z,
    "goalMouthY" as goal_mouth_y,
    "relatedEventId" as related_event_id,
    "relatedPlayerId" as related_player_id,
    "isOwnGoal" as is_own_goal,
    "cardType" as card_type,
    "blockedX" as blocked_x,
    "blockedY" as blocked_y,
    "playerName" as player_name
FROM {{ source('whoscored_db', 'event_main') }} 